### PR TITLE
fix(auth): refresh GitHub App access tokens before invalidating accounts

### LINKED ISSUE #5: GitHub App access token not refreshed; accounts get invalidated after ~8 hours
## Summary

GitHub App user-to-server access tokens obtained via Device Flow expire after ~8 hours by default. The extension does not capture or use the refresh token, so on the first 401 after expiry the account is marked as `invalidated: "revoked"` and the user must sign in again. End users observe this as "auth breaks after about a day."

## Root cause

1. `src/github/auth.ts:80-91` — `accessTokenResponseSchema` only captures `access_token`, `token_type`, `scope`. It drops `expires_in`, `refresh_token`, and `refresh_token_expires_in`.

   ```ts
   const accessTokenResponseSchema = z.union([
     z.object({
       access_token: z.string(),
       token_type: z.string(),
       scope: z.string().optional(),
     }),
     ...
   ]);
   ```

2. `src/storage/accounts.ts:16-29` — `accountSchema` has no fields for `refreshToken`, `expiresAt`, or `refreshTokenExpiresAt`.

3. `src/features/reviewers/index.ts:209-213` — On any 401 the code unconditionally classifies the error as `"revoked"` and calls `markAccountInvalidated`. No refresh is attempted.

   ```ts
   function getAccountInvalidationReason(error) {
     return extractStatus(error) === 401 ? "revoked" : null;
   }
   ```

## Expected behavior

- Access token lifetime and refresh token are persisted at sign-in.
- When the access token is rejected (401) — or proactively before expiry — the extension exchanges the refresh token for a new access token and retries transparently.
- An account is only marked `invalidated` when the refresh itself fails with a terminal error (`bad_refresh_token`, `expired_token` for the refresh token, user-revoked app, etc.).

## Actual behavior

- After ~8 hours the access token returns 401.
- The account is immediately marked `invalidated: "revoked"`.
- User must re-run Device Flow to regain access, even though a valid refresh token existed.

## References

- GitHub docs: [Refreshing user access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/refreshing-user-access-tokens)
- Related code: `src/github/auth.ts`, `src/storage/accounts.ts`, `src/features/reviewers/index.ts`, `entrypoints/options/device-flow-controller.ts`

## Proposed fix outline

1. Extend `accessTokenResponseSchema` to read `expires_in`, `refresh_token`, `refresh_token_expires_in` when present. Treat them as optional so GitHub Apps with "Expire user tokens" disabled still work.
2. Extend `accountSchema` with `expiresAt?`, `refreshToken?`, `refreshTokenExpiresAt?`. Bump settings version and migrate existing accounts (missing fields → treat as non-expiring until next sign-in).
3. Add `refreshAccessToken({ clientId, refreshToken })` in `src/github/auth.ts` using `grant_type=refresh_token`. Map terminal refresh errors to a new `invalidatedReason: "refresh_failed"`.
4. Wrap `fetchPullReviewerSummary` calls in a retry that, on 401 with a valid refresh token, refreshes the token (updating storage), retries once, and only invalidates if refresh fails.
5. Optionally: proactively refresh when `expiresAt - now < ~60s` to avoid user-visible latency on the first row fetch.
6. Tests: unit-test the refresh path (success, `bad_refresh_token`, network error) and the 401→refresh→retry wrapper in reviewers.

## Scope

Auth/accounts layer only. No changes to reviewer rendering.

### PR DESCRIPTION
**Pull request by hon454**
## Summary

- Persist GitHub App refresh-token metadata from Device Flow sign-in and refresh expired access tokens on 401.
- Coordinate refreshes through the background script and move account storage to v4 per-account fragments so token updates do not overwrite other accounts.
- Reuse the same refresh-and-retry behavior for both reviewer-list fetches and the options-page installation refresh flow.

## Why

GitHub App user-to-server access tokens expire after about 8 hours by default. Before this change, the extension dropped the refresh token on sign-in, so the first 401 after expiry invalidated the account and forced the user through Device Flow again. The initial implementation also stored all accounts in one `settings.accounts[]` blob, which made concurrent token refreshes vulnerable to lost updates.

## Changes

- **Auth flow:** `src/github/auth.ts` now captures refresh-token fields from the access-token response and adds `refreshAccessToken()` with terminal vs. transient refresh failure handling.
- **Storage model:** `src/storage/accounts.ts` now migrates to `extensionSettings` v4, keeps account ids in `settings`, and stores each account across `account:profile:*`, `account:auth:*`, and `account:installations:*` keys so account-scoped writes stay isolated.
- **Refresh coordinator:** `src/auth/refresh-coordinator.ts` still dedupes per account in-flight refreshes, but now reads and writes only the target account record.
- **Shared retry path:** `src/auth/account-token-refresh.ts` centralizes 401 refresh-and-retry behavior, invalidation rules, and retry-after-refresh handling.
- **Reviewer UI + options UI:** reviewer list fetches and options-page installation refreshes both use the shared refresh helper, so expired access tokens recover transparently in both flows.
- **Docs and diagnostics:** README, implementation notes, privacy policy, and manual Chrome testing docs now reflect refresh-token storage, v4 account storage, and the new manual refresh scenarios.

## Impact

- User-facing impact: signed-in users stay signed in across normal access-token expiry, and the options page installation refresh path now recovers from expired access tokens as well.
- API/schema impact: storage moved from `extensionSettings` v3 `accounts[]` to v4 `accountIds[]` plus per-account storage fragments; `refresh_failed` remains an explicit invalidation reason.
- Performance impact: the first request after expiry may pay one refresh round trip; subsequent requests reuse the refreshed token.
- Operational or rollout impact: v2/v3 account storage migrates automatically on first read; old builds that only understand the legacy schema should not be used after upgrading.

## Testing

- [x] Unit tests
- [ ] Integration tests
- [ ] Manual testing

### Test details

- Added or expanded automated coverage for refresh token exchange, v2/v3 -> v4 account storage migration, isolated account token updates, refresh coordinator behavior, reviewer-path retry, and options-page installation refresh retry.
- Ran `pnpm typecheck` and `pnpm test` locally after the storage/auth changes.
- GitHub Actions `verify` check is green on the PR branch.
- Manual Chrome smoke for the new expired-token scenarios is documented in `docs/manual-chrome-testing.md` but was not run as part of this PR.

## Breaking Changes

- None for users on the forward upgrade path. This is an internal storage-schema migration.

## Related Issues

Resolves #5

### CODE REVIEW

File: src/storage/accounts.ts [hunk 1]
```diff
@@ -108,6 +152,33 @@ export async function markAccountInvalidated(
...
+export async function updateAccountTokens(
+  accountId: string,
+  tokens: {
+    token: string;
+    refreshToken: string | null;
+    expiresAt: number | null;
+    refreshTokenExpiresAt: number | null;
+  },
+): Promise<void> {
+  const settings = await getSettings();
```
Comment (hon454) [inline src/storage/accounts.ts]: `updateAccountTokens()` reads the full settings blob, patches one account, and writes the whole blob back. Because the coordinator only dedupes per account, concurrent refreshes for account A and account B can both start from the same pre-refresh snapshot, and the later write will erase the other account's rotated refresh token. Since GitHub rotates refresh tokens, that lost write turns into a terminal refresh failure on the next expiry.

File: src/features/reviewers/index.ts [hunk 2]
```diff
@@ -206,10 +200,58 @@ export function bootReviewerListPage(
   });
 }
 
-function getAccountInvalidationReason(
-  error: unknown,
-): "revoked" | "expired" | "unknown" | null {
-  return extractStatus(error) === 401 ? "revoked" : null;
+async function fetchWithRefresh(args: {
```
Comment (hon454) [inline src/features/reviewers/index.ts:204]: This only adds refresh-and-retry to the reviewer-list fetch path. The existing options-page installation refresh flow still calls authenticated GitHub endpoints directly with `account.token`, so once the 8-hour access token expires, that signed-in workflow still breaks even when a valid refresh token exists.

**Review by hon454 — COMMENTED** [review]
Leaving two review comments.

1. Concurrent refreshes for different accounts can overwrite each other's rotated refresh tokens because `settings` is updated via a full read-modify-write cycle.
2. This change only adds token refresh to the reviewer-list path, while the existing options-page installation refresh flow still fails with an expired access token.

File: src/features/reviewers/index.ts (hunk 2 above)
Comment (hon454) [reply src/features/reviewers/index.ts:204]: Fixed in the latest update. I extracted the 401 refresh-and-retry behavior into a shared helper and now use it both for reviewer-list fetches and for the options-page installation refresh flow. After an expired access token, the options page requests a refreshed token through the background coordinator, retries the installation endpoints once, and then persists the refreshed installations. Added a UI-level regression test for this path.

File: src/storage/accounts.ts (hunk 1 above)
Comment (hon454) [reply src/storage/accounts.ts]: Fixed in the latest update. Account storage is now split into v4 metadata plus per-account fragments (`account:profile:*`, `account:auth:*`, `account:installations:*`) instead of rewriting the full `settings.accounts[]` blob. Token refresh now updates only the auth fragment for the target account, so concurrent refreshes for different accounts no longer overwrite each others rotated refresh tokens. Added migration coverage and targeted storage tests as part of the change.

**Comment by hon454** [comment]
Final pre-merge check: PR body is now synced with the final implementation, the storage/auth docs were updated for the v4 account model and refresh scenarios, review threads are resolved, and CI is green.
